# 公共配置文件
# @author <a href="https://github.com/jarvischan666">JarvisChan</a>
# @from <a href="https://jvc.icu">编程导航知识星球</a>
spring:
  application:
    name: matematch-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jvc
    username: root
    password: czbbzc
#    password: 123456
#    password: czb161081167 #azure服务器mysql
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    port: 6379
    host: localhost
    database: 0
  profiles:
    active: dev

server:
  ssl:
    key-store: classpath:httpsKey.p12
    key-alias: anyname
    key-store-password: czbbzc
    key-store-type: PKCS12
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# [编程导航学习圈](https://t.zsxq.com/0emozsIJh) 连接万名编程爱好者，一起优秀！20000+ 小伙伴交流分享、40+ 大厂嘉宾一对一答疑、4000+ 编程问答参考、100+ 各方向编程交流群