name: Java CI CD with Maven and Docker

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          mvn package -DskipTests
      - name: Docker login and push
        run: |
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
          docker build -t matematch-backend:1.0 .
          docker tag matematch-backend:1.0 ${{ secrets.DOCKER_REPOSITORY }}
          docker push ${{ secrets.DOCKER_REPOSITORY }}
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: 22
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          key: '
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEA1GrDkY+WLVoTD65PUwmqTQXH3YIwdXHYsFAnN4J66ie7zLayyKZ7
bNLk+c6pvUUQFwlTqsAo5Bv7s9N4oEfHJUPKNw4RJOlB/EbJ/y4DTcCUfYhcUux35GCuDW
h64ElILLCrdzyV1yNVhLRykQUoAUuXmcn/+cAByGKC+X2O4TCCsDAfncrXlgJ60mgXthVO
7TXVD6QyAH113ZsWTwl0Ndg6FRlWOoYPQ/Wvd77SRtVZLf23xAAFm9EvW37gdzy+PbjAs7
I1QbM318PelCQ/TXcC4/raJdE9CISd8zQXqTvokNhWgWZrb2W+PrllF8loS5Mlh8zqAqAc
yb3ySeYYduUoed2pDivRjkuKURwQ+qD8YDGLpghbgQgwAtvqQrGPw5RWk1kI2afXUvRtB8
Orr/lMLeQWmaQ6wF5xX4ktdmVHrumhAKOCgoctj02Y9rqYwX9yHjk9KPtmp610txcs5lCv
1aebGjCzuXyAzSunBLgjzcJ3jQVRXqKBT520BpslAAAFiIGVg6WBlYOlAAAAB3NzaC1yc2
EAAAGBANRqw5GPli1aEw+uT1MJqk0Fx92CMHVx2LBQJzeCeuonu8y2ssime2zS5PnOqb1F
EBcJU6rAKOQb+7PTeKBHxyVDyjcOESTpQfxGyf8uA03AlH2IXFLsd+Rgrg1oeuBJSCywq3
c8ldcjVYS0cpEFKAFLl5nJ//nAAchigvl9juEwgrAwH53K15YCetJoF7YVTu011Q+kMgB9
dd2bFk8JdDXYOhUZVjqGD0P1r3e+0kbVWS39t8QABZvRL1t+4Hc8vj24wLOyNUGzN9fD3p
QkP013AuP62iXRPQiEnfM0F6k76JDYVoFma29lvj65ZRfJaEuTJYfM6gKgHMm98knmGHbl
KHndqQ4r0Y5LilEcEPqg/GAxi6YIW4EIMALb6kKxj8OUVpNZCNmn11L0bQfDq6/5TC3kFp
mkOsBecV+JLXZlR67poQCjgoKHLY9NmPa6mMF/ch45PSj7ZqetdLcXLOZQr9Wnmxows7l8
gM0rpwS4I83Cd40FUV6igU+dtAabJQAAAAMBAAEAAAGAVqPRbw6893SU78FuU3VOxCnGcs
AGWfD8rDWVOVv8HIPmYsJmO9dD4ohGoum7bBq+TFcejDfiteAAE0H/IokEXlu/ICOZtI97
vZV2EKJI8K7LIkS7O4t9/2W7uHZUICVjze6lkXXhvCWKXR1o2WPcBGM7y5uLz+eUEpKzz2
V6ILmzpH+MdcTlmCccx7NzcG5Sigh6Be44AuEpcSEvwT8e6lNupWp3NFm34kVUs6fehsvA
mzSwfr5vizWQdmZS0e+w/qbYBoRVmbwDIdEgZQOdWDLU0mdlekF/3UryCDJk/hY6m4vVrZ
ROKIu4P4VofAWbgg54Vp9bIaroHIalX8LefHLSX1r7+HBQzxEz/0CPT6vy3v3nixQMI1IG
hFWTs1iY1Il137oOka2dMY52za5XuJ5ncna2BJvG2YVIWZVyS4LsDe6nJkqwldriSzVh0q
n8eAQpQEGc5yBxCMveXv+hkpIhSGd2cuOrywZCTr+yC18ksaw2DzkP89Gs3yP9AxClAAAA
wAgBYTCCv/2BRRiRcv98Jsbg6EZGISCPVVi1/4fK1zmzUO9dJZ8hMeh9/qIJFtWcSiNxTF
haJie8EESrOxwSU6e9qBmX6IGc4VvxOgeOhMaYYaoRzRM+G/bbj7GXjbgzdQk/lgihKEA+
fYF/YOX7qMVuo+S/nGthzfjV+sDwFhm98xxj3Yuo5+7lUbSTYB58+btN3eQH1RTo+kOh5e
6sVOuwtO1lIFCW/PeBwOIORaMbRP+gvcQduVvsRS39yVVafQAAAMEA7DZTwnDMq68xzy6l
DKpghibzlYnCXH3db6q3n4KZq8pGDfcKsrarPch/VUrGNAtyKPkMrsPQJcD8X/HyJWZiNR
pzUPqgiQFZT6hHmacBCpFIZ4v158vbyH5EQl3s0sFZX4WQ6ypdWZsubfgxVW4AfdUsEkKB
DqU13h00UfEOmmDNIvx+zR8th3lch+3ZT4RgtuO50TMxsixiE+VW7CwJY03FeMUVcLVsTZ
GAe0ViSITx0lcmT0goc5+Svs4d1IojAAAAwQDmNiOb0QqsnvNGJnm4xx+lCQwCfD3WuVZl
Sn3+r0mjWhaQ9DBuwUKEg1UoG0rDFX09WbUzBeKzGzu7ZPRA9YZIhXzRMBOHkSQn5u4q3P
Tj7zttbfxl5LSXZDzE3i4UPJiZwxxV7VB5bhinvBfgrQQIEZCUjCzYY5dcDXKoASRWfBkp
GHVszEFwR77ojwUYRNT80jNIiv1ekPVC9CFT6n3ZQ4XKbYXIfYrMRUeLEF7Zx/2n3JhugN
fGLDYWcr8vJhcAAAAQamFydmlzQG1hdGVtYXRjaAECAw==
-----END OPENSSH PRIVATE KEY-----
'
          script: |
            docker pull jarvischan630/matematch-backend:1.0
            docker run --name matematch-backend -d -p 8081:80 jarvischan630/matematch-backend:1.0
            docker stop matematch-backend
            docker rm matematch-backend
            docker run --name matematch-backend -d -p 8081:80 jarvischan630/matematch-backend:1.0
            docker image prune -f
            docker container prune -f